// This file will be auto-generated by Supabase CLI
// Run: pnpm db:generate-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          type: 'club' | 'federation' | 'school' | 'other';
          logo_url: string | null;
          country: string;
          city: string | null;
          contact_email: string | null;
          website: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: 'club' | 'federation' | 'school' | 'other';
          logo_url?: string | null;
          country?: string;
          city?: string | null;
          contact_email?: string | null;
          website?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'club' | 'federation' | 'school' | 'other';
          logo_url?: string | null;
          country?: string;
          city?: string | null;
          contact_email?: string | null;
          website?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: 'admin' | 'official' | 'volunteer';
          invited_by: string | null;
          invited_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role?: 'admin' | 'official' | 'volunteer';
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: 'admin' | 'official' | 'volunteer';
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
        };
      };
      competitions: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          date: string;
          end_date: string | null;
          location: string;
          venue: string | null;
          status: 'draft' | 'published' | 'active' | 'completed' | 'archived';
          settings: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          date: string;
          end_date?: string | null;
          location: string;
          venue?: string | null;
          status?: 'draft' | 'published' | 'active' | 'completed' | 'archived';
          settings?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          description?: string | null;
          date?: string;
          end_date?: string | null;
          location?: string;
          venue?: string | null;
          status?: 'draft' | 'published' | 'active' | 'completed' | 'archived';
          settings?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          competition_id: string;
          name: string;
          event_code: string;
          event_type: 'track' | 'field_vertical' | 'field_horizontal' | 'throw' | 'combined' | 'relay' | 'road';
          gender: 'M' | 'W' | 'X';
          age_group: string;
          round: 'final' | 'semi' | 'heat' | 'qualification';
          scheduled_time: string | null;
          status: string;
          wind_reading: number | null;
          settings: Json;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          competition_id: string;
          name: string;
          event_code: string;
          event_type: 'track' | 'field_vertical' | 'field_horizontal' | 'throw' | 'combined' | 'relay' | 'road';
          gender: 'M' | 'W' | 'X';
          age_group?: string;
          round?: 'final' | 'semi' | 'heat' | 'qualification';
          scheduled_time?: string | null;
          status?: string;
          wind_reading?: number | null;
          settings?: Json;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          competition_id?: string;
          name?: string;
          event_code?: string;
          event_type?: 'track' | 'field_vertical' | 'field_horizontal' | 'throw' | 'combined' | 'relay' | 'road';
          gender?: 'M' | 'W' | 'X';
          age_group?: string;
          round?: 'final' | 'semi' | 'heat' | 'qualification';
          scheduled_time?: string | null;
          status?: string;
          wind_reading?: number | null;
          settings?: Json;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      athletes: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          date_of_birth: string | null;
          gender: 'M' | 'W' | 'X';
          nationality: string;
          club_id: string | null;
          club_name: string | null;
          license_number: string | null;
          wa_athlete_id: string | null;
          profile_image_url: string | null;
          social_links: Json;
          personal_bests: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          date_of_birth?: string | null;
          gender: 'M' | 'W' | 'X';
          nationality?: string;
          club_id?: string | null;
          club_name?: string | null;
          license_number?: string | null;
          wa_athlete_id?: string | null;
          profile_image_url?: string | null;
          social_links?: Json;
          personal_bests?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          date_of_birth?: string | null;
          gender?: 'M' | 'W' | 'X';
          nationality?: string;
          club_id?: string | null;
          club_name?: string | null;
          license_number?: string | null;
          wa_athlete_id?: string | null;
          profile_image_url?: string | null;
          social_links?: Json;
          personal_bests?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      entries: {
        Row: {
          id: string;
          competition_id: string;
          event_id: string;
          athlete_id: string;
          bib_number: string | null;
          seed_mark: string | null;
          seed_mark_value: number | null;
          heat_number: number | null;
          lane_or_position: number | null;
          status: 'registered' | 'confirmed' | 'checked_in' | 'DNS' | 'scratched';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          competition_id: string;
          event_id: string;
          athlete_id: string;
          bib_number?: string | null;
          seed_mark?: string | null;
          seed_mark_value?: number | null;
          heat_number?: number | null;
          lane_or_position?: number | null;
          status?: 'registered' | 'confirmed' | 'checked_in' | 'DNS' | 'scratched';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          competition_id?: string;
          event_id?: string;
          athlete_id?: string;
          bib_number?: string | null;
          seed_mark?: string | null;
          seed_mark_value?: number | null;
          heat_number?: number | null;
          lane_or_position?: number | null;
          status?: 'registered' | 'confirmed' | 'checked_in' | 'DNS' | 'scratched';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Results tables would continue here...
    };
    Views: {};
    Functions: {};
    Enums: {
      organization_type: 'club' | 'federation' | 'school' | 'other';
      organization_role: 'admin' | 'official' | 'volunteer';
      competition_status: 'draft' | 'published' | 'active' | 'completed' | 'archived';
      event_type: 'track' | 'field_vertical' | 'field_horizontal' | 'throw' | 'combined' | 'relay' | 'road';
      event_round: 'final' | 'semi' | 'heat' | 'qualification';
      gender_type: 'M' | 'W' | 'X';
      entry_status: 'registered' | 'confirmed' | 'checked_in' | 'DNS' | 'scratched';
      track_result_status: 'finished' | 'DNS' | 'DNF' | 'DQ' | 'FS';
      vertical_status: 'active' | 'eliminated' | 'retired' | 'NH';
      field_status: 'active' | 'complete' | 'retired' | 'NM' | 'ND';
      vertical_attempt_outcome: 'o' | 'x' | '-' | 'r';
      qualification_mark: 'Q' | 'q' | 'qR' | 'qJ';
    };
  };
}
